_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 48
  WARMUP_ITERS: 2000
  FREEZE_ITERS: 1000
  
  CHECKPOINT_PERIOD: 20

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

TEST:
  EVAL_PERIOD: 60
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/vehicleid/sbs_R50
