_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    LAST_STRIDE: 2

DATASETS:
  NAMES: ("VIPeR",)
  TESTS: ("VIPeR",) #("VIPeR", "PRID", "GRID", "iLIDS", "CUHK01", "CUHK02", "SenseReID",)

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 64

OUTPUT_DIR: logs/temp
